### NC文件读取测试

In [3]:
import netCDF4 as nc4
import numpy as np

data = nc4.Dataset("../../ClimData/new_ws_2015.nc", 'r')

data

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    title: TerraClimate: monthly climate and climatic water balance for global land surfaces
    summary: This archive contains a dataset of high-spatial resolution (1/24°, ~4-km) monthly climate and climatic water balance for global terrestrial surfaces from 1958-2015. These data were created by using climatically aided interpolation, combining high-spatial resolution climatological normals from the WorldClim version 1.4 and version 2 datasets, with coarser resolution time varying (i.e. monthly) data from CRU Ts4.0 and JRA-55 to produce a monthly dataset of precipitation, maximum and minimum temperature, wind speed, vapor pressure, and solar radiation. TerraClimate additionally produces monthly surface water balance datasets using a water balance model that incorporates reference evapotranspiration, precipitation, temperature, and interpolated plant extractable soil water capacity.
    keywor

In [4]:
for i in data.variables.keys():
    print(i)
    print(data.variables[i])

lat
<class 'netCDF4._netCDF4.Variable'>
float64 lat(lat)
    units: degrees_north
    description: Latitude of the center of the grid cell
    long_name: latitude
    standard_name: latitude
    axis: Y
unlimited dimensions: 
current shape = (4320,)
filling on, default _FillValue of 9.969209968386869e+36 used
lon
<class 'netCDF4._netCDF4.Variable'>
float64 lon(lon)
    units: degrees_east
    description: Longitude of the center of the grid cell
    long_name: longitude
    standard_name: longitude
    axis: X
unlimited dimensions: 
current shape = (8640,)
filling on, default _FillValue of 9.969209968386869e+36 used
time
<class 'netCDF4._netCDF4.Variable'>
float64 time(time)
    description: days since 1900-01-01
    units: days since 1900-01-01 00:00:00
    long_name: time
    standard_name: time
    calendar: gregorian
    axis: T
unlimited dimensions: 
current shape = (12,)
filling on, default _FillValue of 9.969209968386869e+36 used
crs
<class 'netCDF4._netCDF4.Variable'>
int16 crs

In [11]:
print(data.variables['temp'][:, 222:225, 512:515])

[[[272.      270.79    272.50998]
  [271.46    272.72998 272.83   ]
  [272.77    273.00998 273.44   ]]

 [[274.16998 272.71    274.19998]
  [273.38    274.41998 274.31   ]
  [274.41    274.44998 274.71   ]]

 [[276.34    274.61    275.88998]
  [275.3     276.11    275.8    ]
  [276.05    275.88998 275.97998]]

 ...

 [[268.35    266.75    268.19   ]
  [267.75998 268.68    268.50998]
  [268.97998 268.91998 269.13998]]

 [[267.88    266.3     267.75   ]
  [267.41    268.35    268.19   ]
  [268.77    268.71    268.94   ]]

 [[267.87    266.35    267.86   ]
  [267.38998 268.38    268.28   ]
  [268.75    268.74    269.00998]]]


In [5]:
# 单位长度测试
for i in range(10):
    print(data.variables['lat'][i], data.variables['lon'][i])

89.97916666666667 -179.97916666666666
89.9375 -179.9375
89.89583333333334 -179.89583333333331
89.85416666666667 -179.85416666666666
89.8125 -179.8125
89.77083333333334 -179.77083333333331
89.72916666666667 -179.72916666666666
89.6875 -179.6875
89.64583333333334 -179.64583333333331
89.60416666666667 -179.60416666666666


In [7]:
round(70.450005 - 70.45, 4)

0.0