### NC文件读取测试

In [12]:
import netCDF4 as nc4
import numpy as np

data = nc4.Dataset("../data/climData/cache/cache.nc", 'r')
for i in data.variables.keys():
    print(i, data.variables[i].shape)
data.variables['lat'][0:10]

lon (700,)
lat (400,)
time (248,)
temp (248, 400, 700)


masked_array(data=[15.05    , 15.150001, 15.25    , 15.35    , 15.45    ,
                   15.55    , 15.650001, 15.75    , 15.85    , 15.95    ],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [4]:
for i in data.variables.keys():
    print(i)
    print(data.variables[i])

lon
<class 'netCDF4._netCDF4.Variable'>
float32 lon(lon)
    units: degrees_east
    long_name: Longitude
unlimited dimensions: 
current shape = (700,)
filling on, default _FillValue of 9.969209968386869e+36 used
lat
<class 'netCDF4._netCDF4.Variable'>
float32 lat(lat)
    units: degrees_north
    long_name: Latitude
unlimited dimensions: 
current shape = (400,)
filling on, default _FillValue of 9.969209968386869e+36 used
time
<class 'netCDF4._netCDF4.Variable'>
int32 time(time)
    units: hours since 1900-01-01 00:00:0.0
    long_name: Time
unlimited dimensions: time
current shape = (248,)
filling on, default _FillValue of -2147483647 used
temp
<class 'netCDF4._netCDF4.Variable'>
int16 temp(time, lat, lon)
    scale_factor: 0.01
    add_offset: 273.15
    _FillValue: -32767
    missing_value: -32767
    units: K
    long_name: Near surface air temperature
unlimited dimensions: time
current shape = (248, 400, 700)
filling on


In [11]:
print(data.variables['temp'][:, 222:225, 512:515])

[[[272.      270.79    272.50998]
  [271.46    272.72998 272.83   ]
  [272.77    273.00998 273.44   ]]

 [[274.16998 272.71    274.19998]
  [273.38    274.41998 274.31   ]
  [274.41    274.44998 274.71   ]]

 [[276.34    274.61    275.88998]
  [275.3     276.11    275.8    ]
  [276.05    275.88998 275.97998]]

 ...

 [[268.35    266.75    268.19   ]
  [267.75998 268.68    268.50998]
  [268.97998 268.91998 269.13998]]

 [[267.88    266.3     267.75   ]
  [267.41    268.35    268.19   ]
  [268.77    268.71    268.94   ]]

 [[267.87    266.35    267.86   ]
  [267.38998 268.38    268.28   ]
  [268.75    268.74    269.00998]]]


In [3]:
# 单位长度测试
for i in range(10):
    print(data.variables['lat'][i], data.variables['lon'][i])

15.05 70.05
15.150001 70.15
15.25 70.25
15.35 70.350006
15.45 70.450005
15.55 70.55
15.650001 70.65
15.75 70.75
15.85 70.850006
15.95 70.950005


In [7]:
round(70.450005 - 70.45, 4)

0.0